export * from './stairs/stairs-shape';
export * from './stairs/player-shape';
export * from './stairs/bumpy-stair-shape';
export * from './stairs/spike-stair-shape';
export * from './stairs/fadeout-stair-shape';
export * from './stairs/collapes-stair-shape';
export * from './stairs/normal-stairs-shape';
export * from './timer-shape';
export * from './status-shape';
